name: reuters-classifier-jupyter
channels:
  - defaults
dependencies:
  - python=3.6
  - scikit-learn=0.22.1
  - cloudpickle=1.2.2
  - pandas=0.25.3
  - pip:
      - mlflow>=1.0
      - papermill==1.2.1
      - pyarrow==0.16.0