id: reuters-classifier
kind: ModelPackaging
spec:
  artifactName: "<fill-in>"
  integrationName: docker-rest
  resources:
    limits:
      cpu: "1.5"
      memory: 4Gi
    requests:
      cpu: "1.5"
      memory: 2Gi
