kind: ModelTraining
id: reuters-classifier
spec:
  model:
    name: reuters-classifier
    version: 1.0.2
  toolchain: mlflow  # MLFlow training toolchain integration
  entrypoint: main
  workDir: pipeline/stages/train
  reference: 1.0.3
  hyperParameters:
    maxwords: "999"
  data:
    - connName: models-output
      localPath: pipeline/stages/train/
      remotePath: /input/reuters-training/
  resources:
    limits:
      cpu: 3
      memory: 2Gi
    requests:
      cpu: 3
      memory: 2Gi
  vcsName: odahu-pipeline-examples